name: deepar_android
description: A new Flutter plugin project.
version: 0.0.1
homepage:

publish_to: "none"


environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  deepar: 
    path: ../deepar    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

 
flutter: 
  plugin:
    platforms:
      android:
        package: com.example.deepar_android
        pluginClass: DeeparAndroidPlugin 